version: '3.9'

networks:
  wp:
    name: wp
    driver: bridge

secrets:

  mysql_root_password:
    file: ./secrets/mysql_root_password.secret
  wp_mysql_password:
    file: ./secrets/wp_mysql_password.secret

services:

  # MariaDB - The open source relational database.
  db:
    image: mariadb:latest
    container_name: wp-db # change for multiple instances
    restart: always

    secrets: 
      - mysql_root_password
      - wp_mysql_password

    networks:
      - wp

    volumes:
      - ./db-data:/var/lib/mysql

    environment:
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_mysql_password

  # WordPress - website builder.
  wordpress:
    image: wordpress:latest
    container_name: wordpress # change for multiple instances
    restart: always

    secrets:
      - wp_mysql_password

    networks:
      - wp

    depends_on:
      - db

    ports:
      - $WPPORTN:80

    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=db
      - WORDPRESS_DB_USER=dbuser
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_mysql_password

    volumes:
      - ./html:/var/www/html

  # Watchtower - automating Docker container base image updates.
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-wp
    restart: always

    networks:
      - wp

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - TZ=$TZ
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 30 5 * * * # Everyday at 5:30
